# Generated by Django 4.2 on 2023-06-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_reported_by_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reported_by_users',
        ),
    ]
